import "server-only";
import { prisma } from "@/lib/prisma";
import { requireMembership } from "@/features/workspaces/services";
import {
  assertCanReadTransactions,
  LIST_PAGE_SIZE,
  type TransactionType,
} from "@/features/transactions/domain";
import type { TransactionRecord } from "./require-transaction-membership";
import { buildListTransactionsWhere } from "./list-transactions-where";

export type ListTransactionsServiceInput = {
  userId: string;
  workspaceId: string;
  accountId?: string;
  categoryId?: string;
  /** Single type (legacy). Prefer `types` from `resolveListTypeFilter`. */
  type?: TransactionType;
  /** When set, filters with `type in (…)`. Empty/undefined = all types incl. fx. */
  types?: TransactionType[];
  from?: string;
  to?: string;
  cursor?: string;
  limit?: number;
};

export type ListedTransaction = TransactionRecord & {
  accountName: string;
  accountWorkspaceId: string;
  counterpartyAccountName: string | null;
  categoryName: string | null;
  createdByDisplayName: string;
  /** True when listed because it hits a local account but registers elsewhere. */
  isExternalToWorkspace: boolean;
  registrationWorkspaceName: string | null;
  /** SPEC-08 H4 — present when this transfer is a goal contribution. */
  goalContribution: {
    contributionId: string;
    goalId: string;
    goalName: string;
    goalKind: "save" | "debt_payoff";
  } | null;
  /** SPEC-18 §4.10 / FR-11 — present when generated by a recurring rule. */
  recurring: {
    ruleId: string;
    ruleName: string;
    scheduledOn: string;
    isDrifted: boolean;
  } | null;
};

export type ListTransactionsResult = {
  items: ListedTransaction[];
  nextCursor: string | null;
};

const MAX_LIMIT = 200;

/**
 * SPEC-05 FR-04 + SPEC-14 FR-05 — Lists transactions of a workspace ordered by
 * `occurredOn` desc, plus txs that affect local accounts but register elsewhere.
 *
 * Invalid cursor → first page (soft-reset, SPEC-05 §4.5).
 */
export async function listTransactions(
  input: ListTransactionsServiceInput,
): Promise<ListTransactionsResult> {
  const { role } = await requireMembership(input.userId, input.workspaceId);
  assertCanReadTransactions(role);

  const limit = Math.min(input.limit ?? LIST_PAGE_SIZE, MAX_LIMIT);

  const localAccountIds = (
    await prisma.financeAccount.findMany({
      where: { workspaceId: input.workspaceId },
      select: { id: true },
    })
  ).map((a) => a.id);

  const filters = buildListTransactionsWhere(input, localAccountIds);

  // Soft-reset: missing / foreign cursor → first page (SPEC-05 §4.5).
  let cursorId = input.cursor;
  if (cursorId) {
    const anchor = await prisma.transaction.findUnique({
      where: { id: cursorId },
      select: { id: true },
    });
    if (!anchor) {
      cursorId = undefined;
    }
  }

  const rows = await prisma.transaction.findMany({
    where: filters,
    orderBy: [
      { occurredOn: "desc" },
      { createdAt: "desc" },
      { id: "desc" },
    ],
    take: limit + 1,
    ...(cursorId ? { skip: 1, cursor: { id: cursorId } } : {}),
    select: {
      id: true,
      workspaceId: true,
      type: true,
      amountCents: true,
      currency: true,
      occurredOn: true,
      description: true,
      categoryId: true,
      accountId: true,
      counterpartyAccountId: true,
      createdByUserId: true,
      createdAt: true,
      updatedAt: true,
      workspace: { select: { name: true } },
      account: { select: { name: true, workspaceId: true } },
      counterpartyAccount: { select: { name: true } },
      category: { select: { name: true } },
      goalContribution: {
        select: {
          id: true,
          goalId: true,
          goal: { select: { name: true, kind: true } },
        },
      },
      recurringRule: { select: { id: true, name: true } },
      scheduledOn: true,
    },
  });

  const hasMore = rows.length > limit;
  const trimmed = hasMore ? rows.slice(0, limit) : rows;

  const creatorIds = [...new Set(trimmed.map((r) => r.createdByUserId))];
  const creators =
    creatorIds.length === 0
      ? []
      : await prisma.user.findMany({
          where: { id: { in: creatorIds } },
          select: {
            id: true,
            name: true,
            displayName: true,
            email: true,
          },
        });
  const nameByUserId = new Map(
    creators.map((u) => [
      u.id,
      u.displayName?.trim() || u.name || u.email,
    ]),
  );

  const items: ListedTransaction[] = trimmed.map((r) => {
    const isExternal = r.workspaceId !== input.workspaceId;
    const recurring =
      r.recurringRule && r.scheduledOn
        ? {
            ruleId: r.recurringRule.id,
            ruleName: r.recurringRule.name,
            scheduledOn: toIsoDate(r.scheduledOn),
            isDrifted: toIsoDate(r.scheduledOn) !== toIsoDate(r.occurredOn),
          }
        : null;
    return {
      id: r.id,
      workspaceId: r.workspaceId,
      type: r.type as TransactionType,
      amountCents: r.amountCents,
      currency: r.currency,
      occurredOn: r.occurredOn,
      description: r.description,
      categoryId: r.categoryId,
      accountId: r.accountId,
      counterpartyAccountId: r.counterpartyAccountId,
      createdByUserId: r.createdByUserId,
      createdAt: r.createdAt,
      updatedAt: r.updatedAt,
      accountName: r.account?.name ?? "",
      accountWorkspaceId: r.account?.workspaceId ?? r.workspaceId,
      counterpartyAccountName: r.counterpartyAccount?.name ?? null,
      categoryName: r.category?.name ?? null,
      createdByDisplayName:
        nameByUserId.get(r.createdByUserId) ?? r.createdByUserId,
      isExternalToWorkspace: isExternal,
      registrationWorkspaceName: isExternal ? r.workspace.name : null,
      goalContribution: r.goalContribution
        ? {
            contributionId: r.goalContribution.id,
            goalId: r.goalContribution.goalId,
            goalName: r.goalContribution.goal.name,
            goalKind: r.goalContribution.goal.kind as "save" | "debt_payoff",
          }
        : null,
      recurring,
    };
  });

  return {
    items,
    nextCursor: hasMore ? trimmed[trimmed.length - 1].id : null,
  };
}

function toIsoDate(d: Date): string {
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, "0");
  const day = String(d.getUTCDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}
